### ISSUE TITLE
Add the ability to add arguments to mutators

### ISSUE THREAD

**Issue by wfeller** [topclaudy/eloquent-mutators#1]
Hi,

Would it be useful to be able to add arguments to accessors / mutators in the same way it's done for validation rules?

I'm sometimes casting attributes to objects and it would be much cleaner to do:
`protected $mutators = ['my_attribute' => 'to_object:' . MyObject::class];`
or even
`protected $mutators = ['my_attribute' => ['to_object' => MyObject::class]];`
instead of
`protected $mutators = ['my_attribute' => ['to_' . MyObject::class]]; // Looks bad`

I currently need to register all the potential objects in my service provider, and I think it kind of sucks:
```
foreach ($classes as $class) {
    Mutator::extend("to_$class", function ($model, $value, $key) use ($class) {
        return new $class($value);
    });
}
```
This would look better:
```
Mutator::extend('to_object', function ($model, $value, $key, string $class) {
    return new $class($value);
};
```
If that's something that could be useful, I can submit a PR to add the ability to have custom parameters in the extend functions.

**Comment by topclaudy** [comment]
I thought about this feature but realized that only scalars, strings (and numeric strings) could get passed as arguments. In your context it would be useful. You may submit a PR and I would merge it in the upcoming release.

**Comment by topclaudy** [comment]
Check the https://github.com/topclaudy/eloquent-mutators/releases/tag/1.0.4 release
