### ISSUE TITLE
Problem with encoding when use lower_case and upper_case mutators.

### ISSUE THREAD

**Issue by wfern** [topclaudy/eloquent-mutators#12]
Hi, i'm having an error when using `lower_case` and `upper_case` mutators.

E.g: `General error: 1366 Incorrect string value: '\xE3\xA9rgio...' for column 'payer_name' at row 1 `. Doing a research I found that the error is caused by `strtolower` and `strtoupper` PHP functions and using `mb_xxx` functions solves the problem. By the way, Laravel uses these `mb_xxx` functions in the support helpers like `Str::lower`. Would be nice to apply these changes to capitalize functions as well.

Thanks man.

**Comment by topclaudy** [comment]
@wfeller Thanks for reporting this. Fixed in 1.0.14
